name: Docker Compose Build Check

on:
  push:
    branches:
      - main # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and test Docker services
        run: |
          cd agent
          python -m venv venv
          source ./venv/bin/activate
          pip install paho-mqtt==1.6.1
          pip install marshmallow
          pip freeze > requirements.txt
          docker compose -f agent/docker/docker-compose.yaml up --build -d
          docker compose -f agent/docker/docker-compose.yaml ps
          # Add any additional tests or commands here
